# Generated by Django 2.2.9 on 2020-02-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='telephone',
            field=models.CharField(max_length=255),
        ),
    ]
