# Generated by Django 2.2.9 on 2020-04-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_auto_20200405_1943'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=128)),
                ('method', models.PositiveSmallIntegerField(choices=[(1, 'GET'), (2, 'POST')])),
                ('time_delta', models.DecimalField(decimal_places=3, max_digits=5)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='telephone',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
