# Generated by Django 2.2.9 on 2020-04-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_auto_20200409_1455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logger',
        ),
    ]
