# Generated by Django 2.2.9 on 2020-01-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
    ]
