# Generated by Django 2.2.9 on 2020-02-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_auto_20200115_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_creation_date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
