# Generated by Django 2.2.9 on 2020-02-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_auto_20200219_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_telephone',
            field=models.CharField(max_length=255),
        ),
    ]
